/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package viewsZoo;

import Modelos.Ave;
import Services.ZooService;
import javax.swing.JOptionPane;

/**
 *
 * @author Rey
 */
public class CrearAve extends javax.swing.JDialog {

    /**
     * Creates new form CrearAve
     */
    ViewZoo viewZoo = new ViewZoo();
    
    public CrearAve(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jRadioButton1.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombreDeEspecie = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelCantidadDeAnimales = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabelCantidadDeHebras = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabelPesoMaximo = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabelMesDeApariamiento = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabelEdadMaxima = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelEstaturaMaxima = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelColorDeLasPlumas = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabelTiempoEnNacer = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabelColorDeLosHuevos = new javax.swing.JLabel();
        jLabelDiametroHuevo = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabelPuedeVolar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreDeEspecie.setText("Nombre de la especie");
        jPanel1.add(jLabelNombreDeEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 20));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 160, -1));

        jLabelCantidadDeAnimales.setText("Cantidad de animales");
        jPanel1.add(jLabelCantidadDeAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 20));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 40, 40));

        jLabelCantidadDeHebras.setText("Cantidad de hembras");
        jPanel1.add(jLabelCantidadDeHebras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 20));
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 40, 40));

        jLabelPesoMaximo.setText("Peso Maximo");
        jPanel1.add(jLabelPesoMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 20));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 160, -1));

        jLabelMesDeApariamiento.setText("Mes de apariamiento");
        jPanel1.add(jLabelMesDeApariamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, 20));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 160, -1));

        jLabelEdadMaxima.setText("Edad Maxima");
        jPanel1.add(jLabelEdadMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, 20));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 160, -1));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        jButtonCancelar.setText("Limpiar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        jLabelEstaturaMaxima.setText("Estatura maxima");
        jPanel1.add(jLabelEstaturaMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 20));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 160, -1));

        jLabelColorDeLasPlumas.setText("Color de las plumas");
        jPanel1.add(jLabelColorDeLasPlumas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, 20));

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 160, -1));

        jLabelTiempoEnNacer.setText("Tiempo en nacer");
        jPanel1.add(jLabelTiempoEnNacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 20));

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 160, -1));

        jLabelColorDeLosHuevos.setText("Color de los huevos");
        jPanel1.add(jLabelColorDeLosHuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 20));

        jLabelDiametroHuevo.setText("Diametro aproximado del huevo");
        jPanel1.add(jLabelDiametroHuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 180, 20));

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 160, -1));

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 160, -1));

        jLabelPuedeVolar.setText("Puede volar");
        jPanel1.add(jLabelPuedeVolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 150, 20));

        jLabel1.setText("Color característico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, 20));

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 160, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Si");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("No");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        String nombre = jTextField1.getText();
        int cantAnimal = jSpinner1.getComponentCount();
        int cantHembras = jSpinner2.getComponentCount();
        double peso = Integer.parseInt(jTextField2.getText());
        String mesApareamiento = jTextField3.getText();
        int edad = Integer.parseInt(jTextField4.getText());
        double estatura = Integer.parseInt(jTextField5.getText());
        String colorPluma = jTextField6.getText();
        int tiempoNacer = Integer.parseInt(jTextField7.getText());
        String colorHuevo = jTextField8.getText();
        double diametroHuevo = Integer.parseInt(jTextField9.getText());
        String colorCaracteristico = jTextField10.getText();
        boolean puedeVolar = true;
        if  (jRadioButton1.isSelected())
            puedeVolar = true;
        if(jRadioButton2.isSelected())
            puedeVolar = false;
       
        
        Ave ave = new Ave(estatura, colorPluma, puedeVolar, colorHuevo, diametroHuevo, tiempoNacer, nombre, cantAnimal, cantHembras, peso, tiempoNacer, edad);
        
        viewZoo.getZooService().agregarNuevaAve(estatura, colorPluma, puedeVolar, colorHuevo, diametroHuevo, tiempoNacer, nombre, cantAnimal, cantHembras, peso, tiempoNacer, edad);
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if(!Character.isLetter(teclaPulsada))
            evt.consume(); 
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if(!Character.isDigit(teclaPulsada))
            evt.consume(); 
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if(!Character.isDigit(teclaPulsada))
            evt.consume(); 
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if(!Character.isDigit(teclaPulsada))
            evt.consume(); 
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if(!Character.isLetter(teclaPulsada))
            evt.consume(); 
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if(!Character.isDigit(teclaPulsada))
            evt.consume(); 
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if(!Character.isLetter(teclaPulsada))
            evt.consume(); 
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if(!Character.isDigit(teclaPulsada))
            evt.consume(); 
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if(!Character.isLetter(teclaPulsada))
            evt.consume(); 
    }//GEN-LAST:event_jTextField10KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearAve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearAve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearAve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearAve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearAve dialog = new CrearAve(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCantidadDeAnimales;
    private javax.swing.JLabel jLabelCantidadDeHebras;
    private javax.swing.JLabel jLabelColorDeLasPlumas;
    private javax.swing.JLabel jLabelColorDeLosHuevos;
    private javax.swing.JLabel jLabelDiametroHuevo;
    private javax.swing.JLabel jLabelEdadMaxima;
    private javax.swing.JLabel jLabelEstaturaMaxima;
    private javax.swing.JLabel jLabelMesDeApariamiento;
    private javax.swing.JLabel jLabelNombreDeEspecie;
    private javax.swing.JLabel jLabelPesoMaximo;
    private javax.swing.JLabel jLabelPuedeVolar;
    private javax.swing.JLabel jLabelTiempoEnNacer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
