/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package viewsZoo;

import Services.ZooService;
import javax.swing.JOptionPane;






/**
 *
 * @author Rey
 */
public class ViewZoo extends javax.swing.JFrame {

    /**
     * Creates new form ViewZoo
     */
    
    private ZooService zooService = new ZooService(null);

    public ZooService getZooService() {
        return zooService;
    }

    public void setZooService(ZooService zooService) {
        this.zooService = zooService;
    }
    
    public ViewZoo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jButtonAgregarMamifero = new javax.swing.JButton();
        jButtonAgregarAve = new javax.swing.JButton();
        jButtonAgregarReptil = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRegistrarEpecie = new javax.swing.JMenu();
        jMenuItemRegiistrarAve = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRegistrarMamifero = new javax.swing.JMenuItem();
        jMenuItemRegistrarMonotrmea = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRegistrarReptil = new javax.swing.JMenuItem();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemEstadoEspecie = new javax.swing.JMenuItem();
        jMenuItemTotalDeAnimalesPorGrupo = new javax.swing.JMenuItem();
        jMenuItemViewMamifero = new javax.swing.JMenuItem();
        jMenuItemViewAves = new javax.swing.JMenuItem();
        jMenuItemViewReptil = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAyda = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zoológico");
        setIconImages(getIconImages());
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Zoológico");

        jButtonAgregarMamifero.setText("Agregar un mamifero");
        jButtonAgregarMamifero.setToolTipText("Entrar una nueva especie");
        jButtonAgregarMamifero.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonAgregarMamiferoMouseMoved(evt);
            }
        });
        jButtonAgregarMamifero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAgregarMamiferoMouseExited(evt);
            }
        });
        jButtonAgregarMamifero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMamiferoActionPerformed(evt);
            }
        });

        jButtonAgregarAve.setText("Agregar un ave");
        jButtonAgregarAve.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonAgregarAveMouseMoved(evt);
            }
        });
        jButtonAgregarAve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAgregarAveMouseExited(evt);
            }
        });
        jButtonAgregarAve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAveActionPerformed(evt);
            }
        });

        jButtonAgregarReptil.setText("Agrgar un reptil");
        jButtonAgregarReptil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarReptilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel2))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAgregarMamifero)
                        .addGap(48, 48, 48)
                        .addComponent(jButtonAgregarAve)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonAgregarReptil)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarMamifero)
                    .addComponent(jButtonAgregarAve)
                    .addComponent(jButtonAgregarReptil))
                .addGap(0, 362, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonAgregarMamifero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonAgregarAve, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonAgregarReptil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuRegistrarEpecie.setText("Registrar una especie");

        jMenuItemRegiistrarAve.setText("Registrar Ave");
        jMenuItemRegiistrarAve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegiistrarAveActionPerformed(evt);
            }
        });
        jMenuRegistrarEpecie.add(jMenuItemRegiistrarAve);
        jMenuRegistrarEpecie.add(jSeparator2);

        jMenuItemRegistrarMamifero.setText("Regitrar Mamifero");
        jMenuItemRegistrarMamifero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarMamiferoActionPerformed(evt);
            }
        });
        jMenuRegistrarEpecie.add(jMenuItemRegistrarMamifero);

        jMenuItemRegistrarMonotrmea.setText("Regitrar Mamifero Monotrema");
        jMenuItemRegistrarMonotrmea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarMonotrmeaActionPerformed(evt);
            }
        });
        jMenuRegistrarEpecie.add(jMenuItemRegistrarMonotrmea);
        jMenuRegistrarEpecie.add(jSeparator1);

        jMenuItemRegistrarReptil.setText("Registrar Reptil");
        jMenuItemRegistrarReptil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarReptilActionPerformed(evt);
            }
        });
        jMenuRegistrarEpecie.add(jMenuItemRegistrarReptil);

        jMenuBar1.add(jMenuRegistrarEpecie);

        jMenuOpciones.setText("Opciones");

        jMenuItemEstadoEspecie.setText("Mostrar estado de las especies");
        jMenuOpciones.add(jMenuItemEstadoEspecie);

        jMenuItemTotalDeAnimalesPorGrupo.setText("Mostrar total de animales por grupo");
        jMenuOpciones.add(jMenuItemTotalDeAnimalesPorGrupo);

        jMenuItemViewMamifero.setText("Mostrar lista de mamiferos");
        jMenuItemViewMamifero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewMamiferoActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemViewMamifero);

        jMenuItemViewAves.setText("Mostrar lista de aves");
        jMenuItemViewAves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewAvesActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemViewAves);

        jMenuItemViewReptil.setText("Mostrar lista de reptiles");
        jMenuItemViewReptil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewReptilActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemViewReptil);

        jMenuItemSalir.setText("Salir ");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSalir);

        jMenuBar1.add(jMenuOpciones);

        jMenuAyda.setText("Ayuda");
        jMenuBar1.add(jMenuAyda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(-1);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jButtonAgregarAveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarAveMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButtonAgregarAveMouseExited

    private void jButtonAgregarAveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarAveMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonAgregarAveMouseMoved

    private void jButtonAgregarMamiferoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMamiferoMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButtonAgregarMamiferoMouseExited

    private void jButtonAgregarMamiferoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMamiferoMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonAgregarMamiferoMouseMoved

    private void jMenuItemRegistrarMonotrmeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarMonotrmeaActionPerformed
        // TODO add your handling code here:
         CrearMamiferoMonotrema crearMamiferoMonotrma = new CrearMamiferoMonotrema(this,true); 
         crearMamiferoMonotrma.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarMonotrmeaActionPerformed

    private void jMenuItemRegiistrarAveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegiistrarAveActionPerformed
        // TODO add your handling code here:
        CrearAve crearAve = new CrearAve(this, true); 
        crearAve.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegiistrarAveActionPerformed

    private void jMenuItemRegistrarMamiferoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarMamiferoActionPerformed
        // TODO add your handling code here:
         CrearMamifero crearMamifero = new CrearMamifero(this,true); 
         crearMamifero.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarMamiferoActionPerformed

    private void jMenuItemRegistrarReptilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarReptilActionPerformed
        // TODO add your handling code here:
        CrearReptil crearReptil = new CrearReptil(this,true); 
         crearReptil.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarReptilActionPerformed

    private void jMenuItemViewMamiferoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewMamiferoActionPerformed
        // TODO add your handling code here:
        ViewMamifero viewMamifero = new ViewMamifero(this,false);
         viewMamifero.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewMamiferoActionPerformed

    private void jMenuItemViewAvesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewAvesActionPerformed
        // TODO add your handling code here:
        ViewAve viewAve = new ViewAve(this,false);
        viewAve.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewAvesActionPerformed

    private void jMenuItemViewReptilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewReptilActionPerformed
        // TODO add your handling code here:
        ViewReptil viewReptil = new ViewReptil(this, false);
        viewReptil.setVisible(true);          
    }//GEN-LAST:event_jMenuItemViewReptilActionPerformed

    private void jButtonAgregarAveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAveActionPerformed
        // TODO add your handling code here:
       CrearAve crearAve = new CrearAve(this, true); 
       crearAve.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarAveActionPerformed

    private void jButtonAgregarMamiferoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMamiferoActionPerformed
        // TODO add your handling code here:
         CrearMamifero crearMamifero = new CrearMamifero(this,true); 
         crearMamifero.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarMamiferoActionPerformed

    private void jButtonAgregarReptilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarReptilActionPerformed
        // TODO add your handling code here:
        CrearReptil crearReptil = new CrearReptil(this,true); 
         crearReptil.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarReptilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewZoo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarAve;
    private javax.swing.JButton jButtonAgregarMamifero;
    private javax.swing.JButton jButtonAgregarReptil;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAyda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemEstadoEspecie;
    private javax.swing.JMenuItem jMenuItemRegiistrarAve;
    private javax.swing.JMenuItem jMenuItemRegistrarMamifero;
    private javax.swing.JMenuItem jMenuItemRegistrarMonotrmea;
    private javax.swing.JMenuItem jMenuItemRegistrarReptil;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTotalDeAnimalesPorGrupo;
    private javax.swing.JMenuItem jMenuItemViewAves;
    private javax.swing.JMenuItem jMenuItemViewMamifero;
    private javax.swing.JMenuItem jMenuItemViewReptil;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JMenu jMenuRegistrarEpecie;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private String jButtonActualizarEspecie() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
